def get_default_test_zones():
    raw_data = [
        ("Redtree Enclave", 8, "black"),
        ("Timberwood Dell", 6, "black"),
        ("Drownhole Fen", 7, "black"),
        ("Razorrock Ravine", 7, "black"),
        ("Mardu", 6, "black"),
        ("Gravemound Slope", 7, "black"),
        ("Whitecleave", 8, "black"),
        ("Sandstone Deep", 7, "black"),
        ("Blackthorn Quarry", 6, "black"),
        ("Wanderers Rest", 6, "black"),
        ("Slithervent Canyon", 8, "black"),
        ("Death-reach Gorge", 7, "black"),
        ("Lymhurst Portal Area", 5, "black"),
        ("Fort Sterling Portal Area", 5, "black"),
        ("Thetford Portal Area", 5, "black"),
        ("Martlock Portal Area", 5, "black"),
        ("Bridgewatch Portal Area", 5, "black"),
        ("Brecilien Portal Area", 5, "black"),
        ("Archers Keep", 6, "black"),
        ("Mage's Rest", 6, "black"),
        ("Morgana's Shadow", 6, "black"),
        ("Guards Wood", 6, "black"),
        ("Blackwood", 6, "black"),
        ("Thornwood", 6, "black"),
        ("Greenwood", 6, "black"),
        ("Aspenwood", 7, "black"),
        ("Eldwood", 8, "black"),
        ("Stonewood", 7, "black"),
        ("Ironwood", 8, "black"),
        ("Deepwood", 7, "black"),
        ("Wetwood", 6, "black"),
        ("Driftwood", 6, "black"),
        ("Saltwood", 6, "black"),
        ("Shorewood", 6, "black"),
        ("Siltwood", 6, "black"),
        ("Claywood", 6, "black"),
        ("Swampwood", 6, "black"),
        ("Bogwood", 6, "black"),
        ("Fenwood", 6, "black"),
        ("Marshwood", 6, "black"),
        ("Mirewood", 6, "black"),
        ("Heathwood", 6, "black"),
        ("Peatwood", 6, "black"),
        ("Gripwood", 6, "black"),
        ("Tanglewood", 7, "black"),
        ("Bramblewood", 7, "black"),
        ("Brushwood", 6, "black"),
        ("Shrubwood", 6, "black"),
        ("Fernwood", 6, "black"),
        ("Ivywood", 6, "black"),
        ("Vinewood", 6, "black"),
        ("Mosswood", 6, "black"),
        ("Lichenwood", 6, "black"),
        ("Fungiwood", 6, "black"),
        ("Sporewood", 6, "black"),
        ("Mouldwood", 6, "black"),
        ("Rootwood", 6, "black"),
        ("Barkwood", 6, "black"),
        ("Twigwood", 6, "black"),
        ("Branchwood", 6, "black"),
        ("Leafwood", 6, "black"),
        ("Budwood", 6, "black"),
        ("Flowerwood", 6, "black"),
        ("Seedwood", 6, "black"),
        ("Nutwood", 6, "black"),
        ("Berrywood", 6, "black"),
        ("Fruitwood", 6, "black"),
        ("Orchardwood", 6, "black"),
        ("Grovewood", 6, "black"),
        ("Copsewood", 6, "black"),
        ("Spinneywood", 6, "black"),
        ("Thickwood", 6, "black"),
        ("Wildwood", 7, "black"),
        ("Primevalwood", 8, "black"),
        ("Creag Garr", 6, "red"),
        ("Runnelvein Bog", 6, "red"),
        ("Saddleback Pass", 6, "red"),
        ("Highland Cross", 3, "red"),
        ("Swamp Cross", 3, "red"),
        ("Mountain Cross", 3, "red"),
        ("Steppe Cross", 3, "red"),
        ("Forest Cross", 3, "red"),
        ("Caerleon Outskirts", 6, "red"),
        ("Axe Head", 5, "red"),
        ("Barkway", 5, "red"),
        ("Birchwood", 5, "red"),
        ("Bleachwood Fens", 5, "red"),
        ("Burnt Oak", 5, "red"),
        ("Deadvein Gulch", 5, "red"),
        ("Dryvein Cross", 5, "red"),
        ("Gorge", 5, "red"),
        ("Grovethorn", 5, "red"),
        ("Murkweald", 6, "red"),
        ("Sunkenbogs", 6, "red"),
        ("Wayward Wood", 5, "red"),
        ("Cairn Camain", 5, "red"),
        ("Cairn Glascore", 5, "red"),
        ("Cairn Gera", 5, "red"),
        ("Cairn Darrow", 5, "red"),
        ("Cairn Tor", 5, "red"),
        ("Breckland", 5, "red"),
        ("Brakebush Wood", 5, "red"),
        ("Longbow Mountain", 5, "red"),
        ("Stony Chimney", 5, "red"),
        ("Rowanwood", 5, "red"),
        ("Oakwood", 5, "red"),
        ("Willow Wood", 5, "red"),
        ("Yew Wood", 5, "red"),
        ("Chestnut Wood", 5, "red"),
        ("Elmwood", 5, "red"),
        ("Ashwood", 5, "red"),
        ("Alderwood", 5, "red"),
        ("Cedarwood", 5, "red"),
        ("Redwood", 5, "red"),
        ("Pine Wood", 5, "red"),
        ("Fir Wood", 5, "red"),
        ("Larchwood", 5, "red"),
        ("Sprucewood", 5, "red"),
        ("Hemlockwood", 5, "red"),
        ("Cypresswood", 5, "red"),
        ("Juniperwood", 5, "red"),
        ("Tamarackwood", 5, "red"),
        ("Dogwood", 5, "red"),
        ("Maplewood", 5, "red"),
        ("Beechwood", 5, "red")
    ]
    zones = []
    for name, tier, biome in raw_data:
        zones.append({
            "id": name.lower().replace(" ", "_"),
            "n": name,
            "t": tier,
            "b": biome,
            "fav": False,
            "p": 0,
            "tags": []
        })
    return zones
