# Este archivo es generado automaticamente y contiene todas las zonas del juego Albion Online.
def get_default_test_zones():
    raw_data = [
        ("0302", 5, "blue"),
        ("0303", 5, "blue"),
        ("0304", 5, "blue"),
        ("1302", 5, "blue"),
        ("1303", 5, "blue"),
        ("1304", 5, "blue"),
        ("2302", 5, "blue"),
        ("2303", 5, "blue"),
        ("2304", 5, "blue"),
        ("3010", 1, "blue"),
        ("3012-HALL-02", 1, "blue"),
        ("3302", 5, "blue"),
        ("3303", 5, "blue"),
        ("3304", 5, "blue"),
        ("4302", 5, "blue"),
        ("4303", 5, "blue"),
        ("4304", 5, "blue"),
        ("Adrens Hill", 5, "yellow"),
        ("Anklesnag Mire", 6, "red"),
        ("Aspenwood", 5, "yellow"),
        ("Astolat", 6, "red"),
        ("Avalanche Incline", 8, "black"),
        ("Avalanche Ravine", 5, "black"),
        ("Bank of Bridgewatch", 1, "blue"),
        ("Bank of Fort Sterling", 1, "blue"),
        ("Bank of Lymhurst", 1, "blue"),
        ("Bank of Martlock", 1, "blue"),
        ("Bank of Thetford", 1, "blue"),
        ("Battlebrae Flatland", 5, "black"),
        ("Battlebrae Grassland", 7, "black"),
        ("Battlebrae Lake", 5, "black"),
        ("Battlebrae Meadow", 7, "black"),
        ("Battlebrae Peaks", 5, "black"),
        ("Battlebrae Plain", 5, "black"),
        ("Bellever Tor", 4, "blue"),
        ("Birchcopse", 4, "blue"),
        ("Birken Fell", 6, "red"),
        ("Black Monastery", 8, "black"),
        ("Blackthorn Quarry", 4, "blue"),
        ("Bleachskull Desert", 6, "black"),
        ("Bleachskull Steppe", 5, "black"),
        ("Bonepool Marsh", 5, "yellow"),
        ("Bowscale Fell", 6, "red"),
        ("Braemore Lowland", 6, "black"),
        ("Braemore Upland", 5, "black"),
        ("Brambleshore Hinterlands", 5, "black"),
        ("Brecilien Copse", 6, "red"),
        ("Brecilien Grove", 5, "yellow"),
        ("Brecilien Thicket", 6, "red"),
        ("Brecilien Weald", 6, "red"),
        ("Brent Knoll", 3, "blue"),
        ("Bridgewatch Market", 1, "blue"),
        ("Bridgewatch Portal Area", 1, "black"),
        ("Broken Fell", 6, "red"),
        ("Brons Hill", 5, "yellow"),
        ("Bryn Gorge", 3, "blue"),
        ("Cairn Camain", 5, "yellow"),
        ("Cairn Cloch", 5, "yellow"),
        ("Cairn Darg", 5, "yellow"),
        ("Cairn Drain", 5, "yellow"),
        ("Cairn Fidair", 5, "yellow"),
        ("Cairn Glascore", 5, "yellow"),
        ("Cairn Gorm", 5, "yellow"),
        ("Camlann", 7, "red"),
        ("Carns Hill", 5, "yellow"),
        ("Caulder Fissure", 5, "yellow"),
        ("Cedarcopse", 4, "blue"),
        ("Champions' Realm", 4, "blue"),
        ("Chillhag", 3, "blue"),
        ("Citadel of Ash", 8, "black"),
        ("Cracked Earth", 3, "blue"),
        ("Creag Dhor", 6, "red"),
        ("Creag Garr", 6, "red"),
        ("Creag Meagir", 6, "red"),
        ("Creag Morr", 6, "red"),
        ("Croker Hill", 5, "yellow"),
        ("Crose Gorge", 3, "blue"),
        ("CrystalRealmDebug", 1, "blue"),
        ("Curlew Fen", 4, "blue"),
        ("DNG-UND-01-MAIN-06", 7, "blue"),
        ("DNG-UND-01-SUB-06", 7, "blue"),
        ("Daemonium Keep", 8, "black"),
        ("Darkbough Snag", 8, "black"),
        ("Darkground Swamp", 6, "red"),
        ("Deadpine Forest", 5, "black"),
        ("Deadvein Gully", 6, "red"),
        ("Deathreach Priory", 8, "black"),
        ("Deathwisp Bog", 7, "black"),
        ("Deathwisp Sink", 7, "black"),
        ("Debug", 1, "black"),
        ("Deeproot Wood", 5, "yellow"),
        ("Deepwood Copse", 7, "black"),
        ("Deepwood Dell", 5, "black"),
        ("Deepwood Gorge", 6, "black"),
        ("Deepwood Pines", 7, "black"),
        ("Dewleaf Fen", 4, "blue"),
        ("Domhain Chasm", 7, "red"),
        ("Driftwood Glen", 6, "black"),
        ("Driftwood Hollow", 7, "black"),
        ("Driftwood Vale", 5, "black"),
        ("Drownfield Course", 5, "black"),
        ("Drownfield Fen", 5, "black"),
        ("Drownfield Mire", 5, "black"),
        ("Drownfield Quag", 7, "black"),
        ("Drownfield Rut", 6, "black"),
        ("Drownfield Sink", 8, "black"),
        ("Drownfield Slough", 6, "black"),
        ("Drownfield Wetland", 6, "black"),
        ("Drownhorse Basin", 5, "yellow"),
        ("Drybasin Oasis", 7, "black"),
        ("Drybasin Riverbed", 5, "black"),
        ("Dryfield Meadow", 4, "blue"),
        ("Drytop Pillars", 6, "black"),
        ("Drytop Riverbed", 6, "black"),
        ("Dryvein Confluence", 7, "black"),
        ("Dryvein Cross", 5, "black"),
        ("Dryvein End", 7, "black"),
        ("Dryvein Oasis", 6, "black"),
        ("Dryvein Plain", 5, "black"),
        ("Dryvein Riverbed", 5, "black"),
        ("Dryvein Steppe", 6, "black"),
        ("Drywater Meadow", 4, "blue"),
        ("Dusklight Fen", 4, "blue"),
        ("Dusktree Swamp", 6, "red"),
        ("Eldersleep", 8, "black"),
        ("Eldon Hill", 5, "yellow"),
        ("Everwinter Crossing", 5, "black"),
        ("Everwinter Expanse", 7, "black"),
        ("Everwinter Gap", 7, "black"),
        ("Everwinter Gorge", 6, "black"),
        ("Everwinter Incline", 8, "black"),
        ("Everwinter Passage", 7, "black"),
        ("Everwinter Peak", 6, "black"),
        ("Everwinter Plain", 6, "black"),
        ("Everwinter Reach", 5, "black"),
        ("Everwinter Shores", 5, "black"),
        ("Eye of the Forest", 8, "black"),
        ("Falsestep Marsh", 5, "yellow"),
        ("Farshore Bay", 5, "black"),
        ("Farshore Cape", 7, "black"),
        ("Farshore Drylands", 7, "black"),
        ("Farshore Esker", 5, "black"),
        ("Farshore Heath", 6, "black"),
        ("Farshore Lagoon", 6, "black"),
        ("Felniks Hill", 5, "yellow"),
        ("Ferndell", 4, "blue"),
        ("Firesink Caldera", 6, "black"),
        ("Firesink Trench", 7, "black"),
        ("Flammog Desolation", 8, "black"),
        ("Flammog Fork", 5, "black"),
        ("Flammog Valley", 6, "black"),
        ("Flatriver Trough", 5, "yellow"),
        ("Flatrock Cliffs", 5, "black"),
        ("Flatrock Plateau", 6, "black"),
        ("Flimmerair Steppe", 6, "red"),
        ("Floatshoal Bight", 7, "black"),
        ("Floatshoal Fissure", 6, "black"),
        ("Floatshoal Floe", 5, "black"),
        ("Flynsdell", 4, "blue"),
        ("Fog Fen", 4, "blue"),
        ("Forest Cross", 2, "blue"),
        ("Forgotten Woods", 1, "blue"),
        ("Fort Sterling Market", 1, "blue"),
        ("Fort Sterling Portal Area", 1, "black"),
        ("Fractured Ground", 3, "blue"),
        ("Frostbite Chasm", 5, "black"),
        ("Frostbite Mountain", 6, "black"),
        ("Frostpeak Ascent", 6, "black"),
        ("Frostpeak Vista", 5, "black"),
        ("Frostseep Crevasse", 7, "black"),
        ("Frostseep Ravine", 5, "black"),
        ("Frostspring Passage", 6, "black"),
        ("Frostspring Volcano", 7, "black"),
        ("Garrow Fell", 6, "red"),
        ("Giantweald Copse", 5, "black"),
        ("Giantweald Dale", 5, "black"),
        ("Giantweald Edge", 7, "black"),
        ("Giantweald Glade", 7, "black"),
        ("Giantweald Roots", 6, "black"),
        ("Giantweald Woods", 6, "black"),
        ("Glacierbreak Summit", 6, "black"),
        ("Glacierfall Canyon", 6, "black"),
        ("Glacierfall Cross", 7, "black"),
        ("Glacierfall Fissure", 8, "black"),
        ("Glacierfall Pass", 8, "black"),
        ("Glacierfall Passage", 5, "black"),
        ("Glacierfall Valley", 7, "black"),
        ("Goffers Knoll", 3, "blue"),
        ("Goldshimmer Plain", 5, "yellow"),
        ("Gravemound Brim", 5, "black"),
        ("Gravemound Cliffs", 7, "black"),
        ("Gravemound Hills", 5, "black"),
        ("Gravemound Knoll", 7, "black"),
        ("Gravemound Slope", 6, "black"),
        ("Greenhollow Copse", 7, "black"),
        ("Greenhollow Vale", 5, "black"),
        ("Greenshore Bay", 8, "black"),
        ("Greenshore Peninsula", 5, "black"),
        ("Gutras Hill", 5, "yellow"),
        ("Gwan Gorge", 3, "blue"),
        ("Haldon Tor", 4, "blue"),
        ("Haytor", 4, "blue"),
        ("Highbole Glen", 6, "red"),
        ("Highland Cross", 2, "blue"),
        ("Highstone Grassland", 5, "black"),
        ("Highstone Loch", 8, "black"),
        ("Highstone Meadow", 5, "black"),
        ("Highstone Mound", 7, "black"),
        ("Highstone Plains", 5, "black"),
        ("Highstone Plateau", 7, "black"),
        ("Hightree Borderlands", 6, "black"),
        ("Hightree Cliffs", 6, "black"),
        ("Hightree Dale", 5, "black"),
        ("Hightree Enclave", 5, "black"),
        ("Hightree Glade", 5, "black"),
        ("Hightree Hillock", 7, "black"),
        ("Hightree Isle", 7, "black"),
        ("Hightree Lake", 5, "black"),
        ("Hightree Levee", 6, "black"),
        ("Hightree Pass", 6, "black"),
        ("Hightree Steep", 5, "black"),
        ("Hightree Strand", 5, "black"),
        ("Hornbeam Wood", 5, "yellow"),
        ("Iceburn Cliffs", 7, "black"),
        ("Iceburn Firth", 5, "black"),
        ("Iceburn Peaks", 6, "black"),
        ("Iceburn Tundra", 7, "black"),
        ("Inis Mon", 5, "yellow"),
        ("Kilmar Tor", 4, "blue"),
        ("Kindlegrass Steppe", 6, "red"),
        ("LEGACY-KEEPER-01", 4, "blue"),
        ("LEGACY-KEEPER-SOLO-01", 6, "blue"),
        ("LEGACY-UNDEAD-01", 7, "blue"),
        ("LEGACY-UNDEAD-02", 7, "blue"),
        ("Larchroad", 3, "blue"),
        ("Lazygrass Plain", 5, "yellow"),
        ("Lewsdon Hill", 5, "yellow"),
        ("Longfen Arms", 6, "black"),
        ("Longfen Marsh", 5, "black"),
        ("Longfen Veins", 7, "black"),
        ("Longmarch Meadow", 4, "blue"),
        ("Longshadow Plain", 5, "yellow"),
        ("Longtimber Glen", 6, "red"),
        ("Lymhurst Market", 1, "blue"),
        ("Lymhurst Portal Area", 1, "black"),
        ("Malag Crevasse", 6, "red"),
        ("Mardale", 6, "red"),
        ("Martlock Market", 1, "blue"),
        ("Martlock Portal Area", 1, "black"),
        ("Mase Knoll", 3, "blue"),
        ("Mawar Gorge", 4, "blue"),
        ("Meltwater Bog", 5, "black"),
        ("Meltwater Channel", 8, "black"),
        ("Meltwater Delta", 6, "black"),
        ("Meltwater Sump", 7, "black"),
        ("Mountain Cross", 2, "blue"),
        ("Mountain Fort", 1, "blue"),
        ("Mudfoot Mounds", 6, "black"),
        ("Mudfoot Sump", 5, "black"),
        ("Munten Fell", 7, "black"),
        ("Munten Rise", 5, "black"),
        ("Munten Tundra", 6, "black"),
        ("Murdergulch Cross", 5, "black"),
        ("Murdergulch Divide", 8, "black"),
        ("Murdergulch Gap", 5, "black"),
        ("Murdergulch Ravine", 8, "black"),
        ("Murdergulch Trail", 7, "black"),
        ("Murkweald", 7, "red"),
        ("Murky Fen", 4, "blue"),
        ("Nightbloom Forest", 6, "red"),
        ("Nightcreak Marsh", 5, "yellow"),
        ("Northstrand Beach", 6, "black"),
        ("Northstrand Dunes", 5, "black"),
        ("Oakcopse", 4, "blue"),
        ("Owlsong Glen", 6, "red"),
        ("PSG-0001", 5, "blue"),
        ("PSG-0002", 5, "blue"),
        ("PSG-H-0001", 7, "blue"),
        ("PSG-H-0002", 7, "blue"),
        ("Parchsand Cliffs", 6, "black"),
        ("Parchsand Drought", 8, "black"),
        ("Parchthroat Plain", 5, "yellow"),
        ("Pen Fenair", 4, "blue"),
        ("Pen Garn", 4, "blue"),
        ("Pen Gent", 4, "blue"),
        ("Pen Kerrig", 4, "blue"),
        ("Pen Uchaf", 4, "blue"),
        ("Pinecopse", 4, "blue"),
        ("Prospector's Hope", 3, "blue"),
        ("Razorrock Bank", 7, "black"),
        ("Razorrock Chasm", 7, "black"),
        ("Razorrock Edge", 6, "black"),
        ("Razorrock Gulch", 8, "black"),
        ("Razorrock Passage", 5, "black"),
        ("Razorrock Ravine", 6, "black"),
        ("Razorrock Valley", 5, "black"),
        ("Razorrock Verge", 7, "black"),
        ("Redlake", 3, "blue"),
        ("Redstone Plain", 5, "yellow"),
        ("Redtree Enclave", 8, "black"),
        ("Rivercopse Crossing", 5, "black"),
        ("Rivercopse Curve", 7, "black"),
        ("Rivercopse Fount", 8, "black"),
        ("Rivercopse Path", 7, "black"),
        ("Roastcorpse Steppe", 6, "red"),
        ("Rowanwood", 5, "yellow"),
        ("Runnel Sink", 7, "red"),
        ("Runnelvein Bog", 6, "black"),
        ("Runnelvein Sink", 7, "black"),
        ("Runnelvein Slough", 5, "black"),
        ("Russerdell", 4, "blue"),
        ("Saddle Tor", 4, "blue"),
        ("Sandgust Cleft", 4, "blue"),
        ("Sandmount Ascent", 8, "black"),
        ("Sandmount Desert", 7, "black"),
        ("Sandmount Esker", 5, "black"),
        ("Sandmount Strand", 5, "black"),
        ("Sandrift Coast", 5, "black"),
        ("Sandrift Dunes", 7, "black"),
        ("Sandrift Expanse", 6, "black"),
        ("Sandrift Fringe", 7, "black"),
        ("Sandrift Prairie", 5, "black"),
        ("Sandrift Shore", 5, "black"),
        ("Sandrift Steppe", 5, "black"),
        ("Scuttlesink Marsh", 8, "black"),
        ("Scuttlesink Mouth", 6, "black"),
        ("Scuttlesink Pools", 5, "black"),
        ("Shaleheath Hills", 6, "black"),
        ("Shaleheath Steep", 7, "black"),
        ("Shiftshadow Expanse", 7, "red"),
        ("Skullmarsh Lower", 5, "black"),
        ("Skullmarsh Upper", 7, "black"),
        ("Skylake Bridge", 6, "black"),
        ("Skylake Hinterlands", 7, "black"),
        ("Skysand Plateau", 5, "black"),
        ("Skysand Ridge", 7, "black"),
        ("Slakesands Canyon", 5, "black"),
        ("Slakesands Mesa", 7, "black"),
        ("Sleetwater Basin", 5, "yellow"),
        ("Slimehag", 3, "blue"),
        ("Slithertail Marsh", 5, "yellow"),
        ("Slowtree Plain", 5, "yellow"),
        ("Smoothfloor Cleft", 4, "blue"),
        ("Snapshaft Trough", 5, "yellow"),
        ("Southgrove Copse", 6, "black"),
        ("Southgrove Escarp", 5, "black"),
        ("Southgrove Thicket", 7, "black"),
        ("Spectral Sump", 6, "red"),
        ("Spindlewood", 5, "yellow"),
        ("Springsump Basin", 5, "black"),
        ("Springsump Melt", 7, "black"),
        ("Springsump Wetland", 6, "black"),
        ("Stagbourne", 3, "blue"),
        ("Steelhide Meadow", 4, "blue"),
        ("Steppe Cross", 2, "blue"),
        ("Stinkhag", 3, "blue"),
        ("Stonelake Fields", 5, "black"),
        ("Stonelake Hillock", 6, "black"),
        ("Stonemouth Bay", 6, "black"),
        ("Stonemouth Northbluff", 5, "black"),
        ("Stonemouth Southbluff", 8, "black"),
        ("Stumprot Swamp", 6, "red"),
        ("Sunfang Approach", 6, "black"),
        ("Sunfang Cliffs", 7, "black"),
        ("Sunfang Dawn", 8, "black"),
        ("Sunfang Ravine", 5, "black"),
        ("Sunfang Wasteland", 7, "black"),
        ("Sunkenbough Spring", 8, "black"),
        ("Sunkenbough Woods", 7, "black"),
        ("Sunstrand Delta", 5, "black"),
        ("Sunstrand Dunes", 6, "black"),
        ("Sunstrand Quicksands", 7, "black"),
        ("Sunstrand Shoal", 5, "black"),
        ("Swamp Cross", 2, "blue"),
        ("Swiftsands Basin", 7, "black"),
        ("Swiftsands Chaparral", 8, "black"),
        ("Swiftsands Plain", 5, "black"),
        ("Tharcal Fissure", 5, "yellow"),
        ("The Cove", 1, "blue"),
        ("Thetford Market", 1, "blue"),
        ("Thetford Portal Area", 1, "black"),
        ("Thirstwater Gully", 7, "black"),
        ("Thirstwater Steppe", 5, "black"),
        ("Thirstwater Waste", 6, "black"),
        ("Thunderrock Ascent", 7, "black"),
        ("Thunderrock Draw", 8, "black"),
        ("Thunderrock Rapids", 6, "black"),
        ("Thunderrock Upland", 7, "black"),
        ("Timberscar Copse", 7, "black"),
        ("Timberscar Dell", 5, "black"),
        ("Timberslope Bridge", 8, "black"),
        ("Timberslope Dell", 6, "black"),
        ("Timberslope Grove", 7, "black"),
        ("Timbertop Dale", 6, "black"),
        ("Timbertop Escarp", 8, "black"),
        ("Timbertop Wood", 7, "black"),
        ("Twinchannel Narrows", 7, "black"),
        ("Unhallowed Cloister", 8, "black"),
        ("VegAnimTest", 3, "blue"),
        ("Vixen Tor", 4, "blue"),
        ("Wailing Bulwark", 8, "black"),
        ("Wanderlure Basin", 5, "yellow"),
        ("Watchwood Bluffs", 6, "black"),
        ("Watchwood Grove", 5, "black"),
        ("Watchwood Lakeside", 6, "black"),
        ("Watchwood Precipice", 5, "black"),
        ("Westweald Shore", 7, "black"),
        ("Westweald Thicket", 5, "black"),
        ("Wetgrave Bog", 5, "black"),
        ("Wetgrave Marsh", 7, "black"),
        ("Wetgrave Swale", 7, "black"),
        ("Whitebank Cross", 5, "black"),
        ("Whitebank Descent", 5, "black"),
        ("Whitebank Ridge", 7, "black"),
        ("Whitebank Shore", 5, "black"),
        ("Whitebank Stream", 5, "black"),
        ("Whitebank Wall", 6, "black"),
        ("Whitecliff Expanse", 7, "black"),
        ("Whitecliff Peak", 6, "black"),
        ("Whitepeak Ascent", 5, "black"),
        ("Whitepeak Spring", 7, "black"),
        ("Whitepeak Tundra", 8, "black"),
        ("Whitewall Pass", 8, "black"),
        ("Whitewall Ridge", 7, "black"),
        ("Widemoor Delta", 5, "black"),
        ("Widemoor End", 6, "black"),
        ("Widemoor Estuary", 5, "black"),
        ("Widemoor Fen", 7, "black"),
        ("Widemoor Flats", 6, "black"),
        ("Widemoor Hills", 6, "black"),
        ("Widemoor Pool", 5, "black"),
        ("Widemoor Shore", 5, "black"),
        ("Widemoor Woods", 6, "black"),
        ("Willow Wood", 5, "yellow"),
        ("Willowshade Hills", 7, "black"),
        ("Willowshade Icemarsh", 5, "black"),
        ("Willowshade Lake", 5, "black"),
        ("Willowshade Mire", 5, "black"),
        ("Willowshade Pools", 6, "black"),
        ("Willowshade Sink", 7, "black"),
        ("Willowshade Wetlands", 5, "black"),
        ("Willowsigh Marsh", 5, "yellow"),
        ("Windgrass Border", 5, "black"),
        ("Windgrass Coast", 6, "black"),
        ("Windgrass Fields", 6, "black"),
        ("Windgrass Gully", 5, "black"),
        ("Windgrass Precipice", 5, "black"),
        ("Windgrass Rill", 5, "black"),
        ("Windgrass Terrace", 7, "black"),
        ("Windripple Fen", 4, "blue"),
        ("Wispwhisper Marsh", 5, "yellow"),
        ("Wyre Forest", 6, "red"),
        ("Yew Wood", 5, "yellow"),
    ]
    zones = []
    for name, tier, biome in raw_data:
        zones.append({
            "id": name.lower().replace(" ", "_"),
            "n": name,
            "t": tier,
            "b": biome,
            "fav": False,
            "p": 0,
            "tags": []
        })
    return zones
